### ISSUE TITLE
Maybe loop on all 123?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_DRV2605#13]
https://forums.adafruit.com/viewtopic.php?f=19&t=148655&p=734064#p734015

**Comment by jimmyz5150** [comment]
I noticed the missing waveforms and supplied Adafruit with a complete listing 1-123. It is from Texas Instruments DRV2605l pdf pg 63-65. (https://www.ti.com/lit/ds/symlink/drv2605l.pdf) I created a single pdf for the waveforms and supplied for revision.
[DRV_WaveformsAll.pdf](https://github.com/adafruit/Adafruit_CircuitPython_DRV2605/files/2948646/DRV_WaveformsAll.pdf). 
Also to be aware there is and additional library associated with the drv2605(L) library 1-7 but drv2605(no L) has 1-6. 
![drv2605l_library_1-7](https://user-images.githubusercontent.com/48389593/54074915-90814880-4266-11e9-9db5-309fc5c9a501.PNG).

Regards,
Jim
 Awesome Minds Awesome Things

**Comment by caternuson** [comment]
Closing. Fixed with #14.
