### ISSUE TITLE
Maybe use all the sequence slots?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_DRV2605#15]
Current code is for 7 slots numbered 0 - 6:
https://github.com/adafruit/Adafruit_CircuitPython_DRV2605/blob/48ba4ab7358518eb0ac6ccb81a23ff706dd859b3/adafruit_drv2605.py#L203

Looks like there are actually 8:

![drv2605_seq_count](https://user-images.githubusercontent.com/8755041/54794194-769b1a80-4c03-11e9-8c0c-11af2b3bb632.png)

![DRV2605_waveform_sequencer](https://user-images.githubusercontent.com/8755041/54794205-8a468100-4c03-11e9-81f6-53d32c6c22ff.jpg)

**Comment by tekktrik** [comment]
Addressed by PR #28!

**Comment by caternuson** [comment]
Yep. Thanks again for the PR.
