### ISSUE TITLE
Set Real Time Value

### ISSUE THREAD

**Issue by Ryce358** [adafruit/Adafruit_CircuitPython_DRV2605#22]
Hi - I am trying to set real time value of the motor.  This capability is referenced in TI's documentation and I have seen a reference somewhere to `.set_realtime_input(0)`, however this doesn't seem to be defined in the module that I can see.  I'm quite new to all things Python/rPi.  I have managed to find in the module that `.mode = 5` sets the mode to RTP but there seems to be no command to set the actual RTP value.  Is it possible with this module or will it require updating?Help appreciated.  Thanks.

**Comment by Ryce358** [comment]
I managed to solve this by using the calling 'self._write_u8(0x02, value)' where value is an 8-bit unsigned integer, if anyone is interested.  It would be great if this was part of the module and it didn't require calling an internal function.  I couldn't work out how to set the mode to unsigned, that's a bit over my head ;)

**Comment by caternuson** [comment]
You can reopen this issue if you want and make it a general request for adding support for the Real-Time Playback (RTP) feature of the DRV2605:
![image](https://user-images.githubusercontent.com/8755041/78272176-08e62780-74c2-11ea-8d02-d88fef08cf0e.png)
